name: instagream
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.0.0
  flutter_svg: ^1.0.3
  tuple: ^2.0.0
  provider: ^6.0.2
  async: ^2.5.0
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.5
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/sample/
    - assets/images/
dependency_overrides:
  platform: ^3.1.0